name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Your first issue! Welcome to the family! I hope you enjoy your stay..."
        pr-message: "Your first pull request! Welcome to the family! I hope you enjoy you stay..."
